//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class hiring
    {
        public int id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> account_id { get; set; }
        public string car_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual car car { get; set; }
    }
}
